### 학습지 생성
POST {{url}}/piece
Content-Type: application/json

{
  "teacherId": 1,
  "worksheetName": "테스트",
  "problemIds": [1003, 1001, 1002, 1038]
}

### 학습지 출제
POST {{url}}/piece?studentIds=1,2,3,4,5,6
Content-Type: application/json

{
  "worksheetId" : 1,
  "teacherId": 1
}

### 학습지 문제 조회
GET {{url}}/piece/problems?pieceId=1
Content-Type: application/json