CREATE TABLE PROBLEM
(
    ID        BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '문제 ID',
    UNIT_CODE INT          NOT NULL COMMENT '문제 유형 코드',
    TYPE      VARCHAR(20)  NOT NULL COMMENT '문제 유형 (주관식, 객관식)',
    DIFFICULTY TINYINT      NOT NULL COMMENT '문제 난이도 (1~5)',
    ANSWER    VARCHAR(255) NOT NULL COMMENT '문제 정답',
    CT_UTC    TIMESTAMP    NOT NULL COMMENT '생성 시간',
    UT_UTC    TIMESTAMP    NOT NULL COMMENT '업데이트 시간'
);

CREATE INDEX IDX_PROBLEM_SEARCH ON PROBLEM (UNIT_CODE, TYPE, DIFFICULTY, ANSWER)