CREATE TABLE WORKSHEET
(
    ID          BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    NAME        VARCHAR(255)  NOT NULL COMMENT '문제지 이름',
    PROBLEM_IDS VARCHAR(1024) NOT NULL COMMENT '문제 ID 목록 (1,2,3,4,5) 이런 형태로 저장됨',
    TEACHER_ID  BIGINT        NOT NULL COMMENT '선생님 ID',
    CT_UTC      TIMESTAMP     NOT NULL COMMENT '생성 시간',
    UT_UTC      TIMESTAMP     NOT NULL COMMENT '업데이트 시간',
    UNIQUE (TEACHER_ID, NAME)
);

CREATE TABLE ASSIGNED_WORKSHEET
(
    ID                  BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT 'ID',
    WORKSHEET_ID        BIGINT    NOT NULL COMMENT '문제지 ID',
    STUDENT_ID          BIGINT    NOT NULL COMMENT '학생 ID',
    SUBMITTED_ANSWERS   TEXT COMMENT '제출한 답안',
    PROBLEM_EVALUATIONS VARCHAR(128) COMMENT '문제 정답 여부 (0,1,0,1) 맞았으면 1 틀렸으면 0',
    CORRECT_CNT         INT COMMENT '맞춘 갯수',
    CT_UTC              TIMESTAMP NOT NULL COMMENT '생성 시간',
    UT_UTC              TIMESTAMP NOT NULL COMMENT '업데이트 시간',
    UNIQUE (WORKSHEET_ID, STUDENT_ID)
);
